name: killjoy_lints
description: "Collection of lints with hardcore tuning."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1

dependencies:

dev_dependencies:

topics:
  - lints
  - linter
  - analyzer
  - code-style
  - analysis